ALTER TABLE proyecto_detalle
ADD COLUMN IF NOT EXISTS departamento_id INTEGER REFERENCES departamentos(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS latitud NUMERIC(10, 6),
ADD COLUMN IF NOT EXISTS longitud NUMERIC(10, 6),
ADD COLUMN IF NOT EXISTS direccion TEXT,
ADD COLUMN IF NOT EXISTS monto_final NUMERIC(15, 2);
